name: komikku_flutternew
description: Aplikasi pembaca komik dengan nuansa islami
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dart_json_mapper: ^2.0.2
  flutter_riverpod: ^2.5.1

  #charts flutter
  charts_flutter: ^0.12.0

  #carousel slider
  carousel_slider: ^4.2.1

  #calendar
  table_calendar: ^3.0.8

  # UI Components & Styling
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Icons
  lucide_icons: ^0.257.0

  # Navigation
  go_router: ^12.1.1

  # Forms & Validation
  form_validator: ^1.0.0

  # Notifications
  fluttertoast: ^8.2.4

  # Utilities
  intl: ^0.17.0
  uuid: ^4.2.1

  # HTTP (untuk future API integration)
  http: ^1.1.2
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  overlay_support: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
